# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/2048game/2048game.cache/wt [current_project]
set_property parent.project_path D:/2048game/2048game.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  D:/2048game/2048game.srcs/sources_1/new/random.v
  D:/2048game/2048game.srcs/sources_1/new/vga.v
  D:/2048game/2048game.srcs/sources_1/new/shave.v
  D:/2048game/2048game.srcs/sources_1/new/seg.v
  D:/2048game/2048game.srcs/sources_1/new/move.v
  D:/2048game/2048game.srcs/sources_1/new/clkdiv.v
  D:/2048game/2048game.srcs/sources_1/new/gen.v
  D:/2048game/2048game.srcs/sources_1/new/top_game.v
}
read_xdc D:/2048game/2048game.srcs/constrs_1/new/2048_root.xdc
set_property used_in_implementation false [get_files D:/2048game/2048game.srcs/constrs_1/new/2048_root.xdc]

synth_design -top game -part xc7a35tcpg236-1
write_checkpoint -noxdef game.dcp
catch { report_utilization -file game_utilization_synth.rpt -pb game_utilization_synth.pb }
